POST http://localhost:3000/users
content-type: application/json

{ "name": "sаааааааааааа",
  "about": "dfdfdf",
  "avatar": "ssdsdsd"}

###

GET http://localhost:3000/users

###
GET http://localhost:3000/users/62f15900ac298b2be1689a03

###
PATCH http://localhost:3000/users/me

{ "name": "sаааааааааааа",
  "about": "dfdfdf"}

###
GET http://localhost:3000/cards

###

POST http://localhost:3000/cards
content-type: application/json

{ "name": "samplesdssdsdsdsdd",
  "link": "dfdfdf"}

###
DELETE http://localhost:3000/cards/62f140bb584915f737c2b936